spring:
  application:
    name: ${APP_NAME:backend}

  datasource:
    # 数据源配置
    driver-class-name: ${mediwise.datasource.driver-class-name}
    # 数据库连接地址
    url: jdbc:mysql://${mediwise.datasource.host}:${mediwise.datasource.port}/${mediwise.datasource.database}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai}
    # 数据库用户名
    username: ${mediwise.datasource.username}
    # 数据库密码
    password: ${mediwise.datasource.password}

  servlet:
    multipart:
      # 文件上传配置
      max-file-size: 10MB
      max-request-size: 20MB

server:
  port: 9191  # 服务端口

# 智谱GLM配置
glm:
  api-key: ${mediwise.glm.api-key} # Placeholder for GLM API Key
  url: ${mediwise.glm.url}

app:
  jwt:
    secret-key: ${mediwise.jwt.secret-key}  # JWT 密钥，必须为 32 字符 - Placeholder
    ttl: ${mediwise.jwt.ttl}  # 24小时有效期，单位毫秒
    token-name: ${mediwise.jwt.token-name}  # JWT Token 名称

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true  # 自动驼峰命名转换
  mapper-locations: classpath*:/mapper/**/*.xml  # XML 映射文件路径

springdoc:
  api-docs:
    # OpenAPI 文档路径
    path: /v3/api-docs
  swagger-ui:
    # Swagger UI 页面路径
    path: /swagger-ui.html
knife4j:
  # 启用 Knife4j
  enable: true
  # 开发环境下设置为 false
  production: false

logging:
  level:
    com:
      wtu:
        # 日志级别
        mapper: debug
        service: info
        controller: info