spring:
  application:
    name: backend

  datasource:
    # 数据源配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库连接地址
    url: jdbc:mysql://47.121.181.198:3306/medi_wise?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    # 数据库用户名
    username: root
    # 数据库密码
    password: 123456

  servlet:
    multipart:
      # 文件上传配置
      max-file-size: 10MB
      max-request-size: 20MB

server:
  port: 9191  # 服务端口

# 智谱GLM配置
glm:
  api-key: 6162ebc0805a4405ae8e29b94728905f.udduhRdonF2Pxa1K
  url: https://open.bigmodel.cn/api/paas/v4/chat/completions

app:
  jwt:
    secret-key: 12345678901234567890123456789012  # JWT 密钥，必须为 32 字符
    ttl: 86400000  # 24小时有效期，单位毫秒
    token-name: token  # JWT Token 名称

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true  # 自动驼峰命名转换
  mapper-locations: classpath*:/mapper/**/*.xml  # XML 映射文件路径

springdoc:
  api-docs:
    # OpenAPI 文档路径
    path: /v3/api-docs
  swagger-ui:
    # Swagger UI 页面路径
    path: /swagger-ui.html
knife4j:
  # 启用 Knife4j
  enable: true
  # 开发环境下设置为 false
  production: false

logging:
  level:
    com:
      wtu:
        # 日志级别
        mapper: debug
        service: info
        controller: info